before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: version_release
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
gomod:
  proxy: false
release:
  ids:
    - version_release
  mode: keep-existing
  name_template: '{{.Tag}}'
brews:
  - name: bsuir-schedule
    tap:
      owner: moonkracker
      name: homebrew-tap
    folder: Formula
    ids:
      - version_release
    description: "Get BSUIR schedule"